version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: data-server
    environment:
      POSTGRES_USER: athebyme
      POSTGRES_PASSWORD: EgHuG808k1
      POSTGRES_DB: storage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - goapp-network

volumes:
  pgdata:
networks:
  goapp-network:
    driver: bridge
